### ISSUE TITLE
Year in Review

### ISSUE THREAD

**Issue by geekygirlsarah** [lgbtq/lgbtq-tech-podcast#10]
This could either be prominent tech-related events that happened in 2015, or prominent LGBTQ-related events, or perhaps some combination of both? Panel could discuss how it's changed tech/LGBTQ life.

(Perhaps for December?)

(Perhaps for the first episode?)

**Comment by mfeckie** [comment]
I like the idea, I think first episode is too soon though.  Would be nice to have an episode or two under the belt before doing 'year in review'.

I like the idea mid/late December though

**Comment by ignu** [comment]
I like this!

I'd vote for it being whatever tech things matter to each panelist, LGBTQ issue or not.

**Comment by mfeckie** [comment]
Closing this now it's been released
