### ISSUE TITLE
Code of Conduct/Etiquette Tips

### ISSUE THREAD

**Issue by ignu** [lgbtq/lgbtq-tech-podcast#2]
Add a static page to the site with a code of conduct and general etiquette tips.

**Comment by RussTheAerialist** [comment]
Should we develop what those should be here in the issue?

**Comment by mfeckie** [comment]
Happy to discuss here

**Comment by RussTheAerialist** [comment]
My main two points would be "Be Respectful" and "Be Authentic"

**Comment by ignu** [comment]
don't name drop people in the slack without permission - they might not be out
don't refer to a conversation you heard in slack unless you have permission- they might not want that conversation shared

**Comment by mfeckie** [comment]
Those are great points @ignu
